INSERT INTO [dbo].[AnomalyDet01_Scalar] ([Scalar_Id], [Name], [Unit]) VALUES (1, N'Height                                            ', N'Kg                                                ')
INSERT INTO [dbo].[AnomalyDet01_Scalar] ([Scalar_Id], [Name], [Unit]) VALUES (2, N'Weight                                            ', N'Meter                                             ')
INSERT INTO [dbo].[AnomalyDet01_Scalar] ([Scalar_Id], [Name], [Unit]) VALUES (3, N'Age                                               ', N'Year                                              ')
INSERT INTO [dbo].[AnomalyDet01_Scalar] ([Scalar_Id], [Name], [Unit]) VALUES (4, N'Head Circumference                                ', N'cm                                                ')
INSERT INTO [dbo].[AnomalyDet01_Scalar] ([Scalar_Id], [Name], [Unit]) VALUES (5, N'Length                                            ', N'cm                                                ')
INSERT INTO [dbo].[AnomalyDet01_Scalar] ([Scalar_Id], [Name], [Unit]) VALUES (6, N'BMI                                               ', N'                                                  ')
INSERT INTO [dbo].[AnomalyDet01_Scalar] ([Scalar_Id], [Name], [Unit]) VALUES (7, N'Age(Month)                                        ', N'Month                                             ')
